WonderShopp.UI/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WonderShopp.Core.Contracts;
using WonderShopp.Core.Models;
using WonderShopp.Services;

namespace WonderShopp.UI.Controllers
{
    public class CartController : Controller
    {
        ICartService cartService;
        IOrderService orderService;
        IRepository<Customer> customers;
        public CartController(ICartService CartService, IOrderService OrderService, IRepository<Customer> Customers)
        {
            this.cartService = CartService;
            this.orderService = OrderService;
            this.customers = Customers;
        }
        public ActionResult Index()
        {
            var model = cartService.GetCartItems(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToCart(string Id) {
            cartService.AddToCart(this.HttpContext, Id);
            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromCart(string Id)
        {
            cartService.RemoveFromCart(this.HttpContext, Id);
            return RedirectToAction("Index");
        }
        public PartialViewResult CartSummary()
        {
            var cartSummary = cartService.GetCartSummary(this.HttpContext);
            return PartialView(cartSummary);
        }
        [Authorize]
        public ActionResult Checkout()
        {
          Customer customer = customers.Collection().FirstOrDefault(c => c.Email == User.Identity.Name);
            if(customer != null)
            {
                Order order = new Order()
                {
                    Email = customer.Email,
                    State = customer.State,
                    Street = customer.Street,
                    FirstName = customer.FirstName,
                    LastName = customer.LastName,
                    ZipCode = customer.ZipCode
                };
                return View(order);

            }
            else
            {
                return RedirectToAction("Error");
            }
            
        }
        [HttpPost]
        public ActionResult Checkout(Order order)
        {
            var cartItems = cartService.GetCartItems(this.HttpContext);
            order.OrderStatus = "Order Created";
            order.Email = User.Identity.Name;
            //process the payment via 3rd
            order.OrderStatus = "Payment Processed";
            orderService.CreateOrder(order, cartItems);
            cartService.ClearCart(this.HttpContext);
            return RedirectToAction("Thankyou", new {OrderId = order.Id});
        }
        public ActionResult Thankyou(string OrderId)
        {
            ViewBag.OrderId = OrderId;
            return View();
        }
    }
}

WonderShopp.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WonderShopp.Core.Contracts;
using WonderShopp.Core.Models;
using WonderShopp.Core.ViewModels;

namespace WonderShopp.UI.Controllers
{
    public class HomeController : Controller
    {
        IRepository<Product> context;
        IRepository<ProductCategory> productCategories;
        public HomeController(IRepository<Product> productContext, 
            IRepository<ProductCategory> categoryContext)
        {
            context = productContext;
            productCategories = categoryContext;
        }
        public ActionResult Index(string Category = null)
        {
            List<Product> products;
            List<ProductCategory> categories = productCategories.Collection().ToList();
            if(Category == null)
            {
                products = context.Collection().ToList();
            }
            else
            {
                products = context.Collection().Where(p => p.Category == Category).ToList();    
            }
            ProductListVM model = new ProductListVM();
            model.Products = products;
            model.ProductCategories = categories;
            return View(model);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WonderShopp.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WonderShopp.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WonderShopp.UI/Views/Home/Index.cshtml
@model WonderShopp.Core.ViewModels.ProductListVM
@{
    ViewBag.Title = "Home Page";
}
<div class="container">
    <h1>Products</h1>
    <div class="">
        <h4>Filter By Category</h4>
        <div class="list-group">
            @Html.ActionLink("All", "Index", null,
           new
                {
                    @class = Request["Category"] == null ? "list-group-item-action active"
           : "list-group-item list-group-item-action"
                })
            @foreach (var cat in Model.ProductCategories)
            {
                @Html.ActionLink(cat.Category, "Index",
               new { Category = cat.Category }, new
                    {
                        @class = Request["Category"] == null ?
               "list-group-item-action active" :
               "list-group-item list-group-item-action"
                    })
            }
        </div>
    </div>
    <div class="">
        @foreach (var item in Model.Products)
        {
            <div class="row">
                <div class="product">
                    <div class="col-md-12">
                        <img class="img-fluid image" src="~/Content/ProductImages/@item.Image" />
                    </div>
                    <div class="col-md-12">
                        <strong>@Html.ActionLink(item.Name, "Details", new { id = item.Id })</strong>
                    </div>
                    <div class="col-md-12">
                        <p>@item.Description</p>
                    </div>
                    <div class="col-md-12">
                        <h4>R @item.Price</h4>
                    </div>
                    <div class="col-md-12">
                        <a href="@Url.Action("addToCart","Cart", new {Id = item.Id})" 
                           class="btn btn-success">Add To Cart</a>
                    </div>
                </div>
            </div>
        }
    </div>

  </div>
<style>
    .product {
        display: inline-block;
        width:100%;
    }
</style>